@startuml name
start
    :read input file(.hql);
    :定型に整形;
    if (CREATE TABLE句がある) then (True)

        :trino_ddl += CREATE TABLE tablename(;
        if ("CREATE TABLE"の後に空白文字のみ挟んで"("がある) then (True)
            :columsに()の中身を格納;

            while (column in columns)

                if (typeが指定範囲内) then (True)
                    :trino_ddl += 
                    column type; 
                else (False)
                    :Error出力;
                    end
                endif  

            endwhile

        else (False)
            if ("'LIKE tablename'のフォーマットになっている")
                :trino_ddl += 
                LIKE tablename;
            else (False)
                :Error出力;
                end
            endif
        endif

        if (TABLE PROPERTIES) then (True)
            if (WITHが既にある) then (True)
                :trino_ddl += 
                ,\n  partitioned_by = ARRAY['dt'];
            else (False)
                :trino_ddl += 
                ")\nWITH(\n  partitioned_by = ARRAY['dt']";
            endif
        endif
        if (DATA FORMAT) then (True)
            if (WITHが既にある) then (True)
                :trino_ddl += 
                ",\n  format = 'xxx'";
            else (False)
                :trino_ddl += 
                ")\nWITH(\n  format = 'xxx'";
            endif

        endif
            :trino_ddl += )with(;;

            while (property in properties)

                if (TABLEPROPERTIES) then (True)
                    :convert;
                    :trino_ddl +=;
                elseif (CLUSTERED) then (True)
                    :convert;
                    :trino_ddl +=;
                elseif (SORTED) then (True)
                    :convert;
                    :trino_ddl +=;
                elseif (PARTITIONED) then (True)
                    :convert;
                    :trino_ddl +=;
                else (False)
                    :Error出力;
                    end
                endif

            endwhile
        



    elseif (SHOW TABLES) then (True)
        :Convert;
        :trino_ddl +=;

    elseif (SHOW PARTITIONS) then (True)
        :Convert;
        :trino_ddl +=;

    elseif (DESCRIBE) then (True)
        :Convert;
        :trino_ddl +=;

    elseif (len(columns) <= 1) then (True)
        if (FUNCTIONS or USE or EXPLAIN) then (True)
            :Convert;
            :trino_ddl +=;
        else (False)
            :Error出力;
        end
        endif

    else (False)
        :Error出力;
        end

    endif

    :write output file(.sql);


end
@enduml